import { Html, Head, Main, NextScript } from 'next/document';
import {Popup} from "../components/UI/Popup";

export default function Document() {
    return (
        <Html>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/assets/100chasov.ico" />
            </Head>
            <body>
            <Main />
            <NextScript />
            </body>
        </Html>
    )
}